<?xml version="1.0"?>
<package format="3">
  <name>control</name>
  <version>0.0.0</version>
  <description>Small console control application for MAVROS and uXRCE-DDS.</description>
  <maintainer email="hannesmueller99@t-onlinde.de">hannes</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>px4_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>