<?xml version="1.0"?>
<package format="3">
  <name>drone_vision_pose_publisher</name>
  <version>0.0.1</version>
  <description>Direct vision pose publisher for MAVROS/PX4 using AprilTag detections.</description>

  <maintainer email="hannesmueller99@t-online.de">hannes</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>isaac_ros_apriltag_interfaces</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>mavros</exec_depend>
  <exec_depend>gscam</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>